# Generated by Django 4.1 on 2022-08-29 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoas',
            name='dizimista',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='funcao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funcao_que_exerce', to='cadastros.cargo_funcao'),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='mae',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='pai',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='sexo',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='situacao',
            field=models.CharField(choices=[('Membro', 'Membro'), ('Congregado', 'Congregado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
