# Generated by Django 4.1 on 2022-08-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_pessoas_dizimista_alter_pessoas_funcao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoas',
            name='nivel_escolaridade',
            field=models.CharField(blank=True, choices=[('Analfabeto', 'Analfabeto'), ('Até 5º ano', 'Até 5º ano'), ('5º ano complte', '5º ano completo'), ('6º ao 9º ano do Fundamental', '6º ao 9º ano do Fundamental'), ('Fundamental Completo', 'Fundamental Completo'), ('Médio Incompleto', 'Médio Incompleto'), ('Médio Completo', 'Médio Completo'), ('Superior Incompleto', 'Superior Incompleto'), ('Superior Completo', 'Superior Completo'), ('Mestrado', 'Mestrado'), ('Doutorado', 'Doutorado'), ('ignorado', 'ignorado')], max_length=60, null=True),
        ),
    ]
