# Generated by Django 4.1 on 2022-08-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0003_pessoas_nivel_escolaridade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoas',
            name='dizimista',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='nivel_escolaridade',
            field=models.CharField(blank=True, choices=[('Analfabeto', 'Analfabeto'), ('Até 5º ano', 'Até 5º ano'), ('5º ano complte', '5º ano completo'), ('Fundamental Completo', 'Fundamental Completo'), ('Médio Incompleto', 'Médio Incompleto'), ('Médio Completo', 'Médio Completo'), ('Superior Incompleto', 'Superior Incompleto'), ('Superior Completo', 'Superior Completo'), ('Mestrado', 'Mestrado'), ('Doutorado', 'Doutorado'), ('Ignorado', 'Ignorado')], max_length=60, null=True),
        ),
    ]
