# Generated by Django 4.1 on 2022-09-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igreja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=250)),
                ('titular', models.CharField(max_length=120)),
                ('banco', models.CharField(max_length=120)),
                ('chave_pix', models.CharField(blank=True, max_length=120, null=True)),
                ('tipo_conta', models.CharField(blank=True, choices=[('Conta corrente', 'Conta corrente'), ('Conta poupança', 'Conta poupança')], max_length=120, null=True)),
                ('agencia', models.CharField(blank=True, max_length=100, null=True)),
                ('conta', models.CharField(blank=True, max_length=100, null=True)),
                ('variacao', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'doacoes',
                'db_table': 'doacoes',
            },
        ),
        migrations.CreateModel(
            name='SobreIgreja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(choices=[('Nossa visão', 'Nossa visão'), ('Em que cremos', 'Em que cremos'), ('Hstória', 'História'), ('outro', 'outro')], max_length=100)),
                ('titulo_sobre', models.CharField(blank=True, max_length=120, null=True)),
                ('sub_titulo_sobre', models.CharField(blank=True, max_length=120, null=True)),
                ('sobre', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'sobreigreja',
                'db_table': 'sobreigreja',
            },
        ),
    ]
