# Generated by Django 4.1 on 2022-09-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igreja', '0002_doacoes_sobreigreja'),
    ]

    operations = [
        migrations.AddField(
            model_name='doacoes',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='img/doacoes'),
        ),
    ]
