# Generated by Django 4.1 on 2022-09-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igreja', '0003_doacoes_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacoes',
            name='banco',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='doacoes',
            name='descricao',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='doacoes',
            name='titular',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
