# Generated by Django 4.1 on 2022-09-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igreja', '0004_alter_doacoes_banco_alter_doacoes_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doacoes',
            name='obs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doacoes',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='img/doacoes/'),
        ),
    ]
