# Generated by Django 4.1 on 2022-09-04 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('igreja', '0005_doacoes_obs_alter_doacoes_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doacoes',
            name='obs',
        ),
    ]
