# Generated by Django 4.1 on 2022-09-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igreja', '0006_remove_doacoes_obs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contatos_Msg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lido', models.BooleanField(default=False)),
                ('respondido', models.BooleanField(default=False)),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('msg', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'contatos_msg',
                'db_table': 'contatos_msg',
            },
        ),
    ]
