# Generated by Django 4.1 on 2022-09-04 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('igreja', '0007_contatos_msg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contatos_msg',
            old_name='msg',
            new_name='mensagem',
        ),
    ]
